spring:
  data:
    elasticsearch:
      cluster-name: es-search
      cluster-nodes: 192.168.2.76:9300
      repositories:
        enabled: true
server:
  port: 8989

search-config:
  label-mapping-file: "label-mapping-02"